#mariadb ??
spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url : jdbc:mariadb://localhost:3306/profile
        username: jdp
        password: jdp1q2w
    mvc: 
        view: 
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    #스프링부트 자동빌드
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: true

# mybatis
mybatis:
    mapper-locations: mapper/**/*.xml

