#mariadb ??
spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url : jdbc:mariadb://localhost:3306/profile
        username: jdp
        password: jdp1q2w
    mvc: 
        view: 
            prefix: /WEB-INF/jsp/
            suffix: .jsp

# mybatis
mybatis:
    mapper-locations: mapper/**/*.xml